### ISSUE TITLE
Script works, but not banning IP

### ISSUE THREAD

**Issue by Yokutto** [karek314/ddos-deflate-nginx-cloudflare#1]
Hi, i installed this script and it works as well. But its not banning IP address attacking the server. 
![image](https://user-images.githubusercontent.com/16729837/34617187-b2694222-f221-11e7-8399-36985ebc41f7.png)
i use it with cloudflare.

**Comment by karek314** [comment]
Hi,
As blocking possibilities are limited because of connections coming from cloudflare servers. Only what we know is ip passed in request header from Cloudflare. Thus those connections still will reach your nginx server, will appear in access.log so as well in connections count feature. However, those should be dropped with 403 error, it still cause some load for nginx, but it prevents load on database and your application engine.

You can check
cd /var/logs
grep -r '" 403' *
or
grep -r "ip_of_attacker" *

Let me know if attacker is dropped with 403, if not i will need to look into that. Possibility paste some logs with trimmed ip.

I will leave it open until you confirm.

**Comment by Yokutto** [comment]
I used the `CF-Connecting-IP` header to know real user IP. I used the code from https://blog.cloudflare.com/an-introduction-to-javascript-based-ddos/ to stress my nginx connections and i don't get banned. When i use grep it only returns 403 errors set on forbidden folders, the attacker ip don't get banned

**Comment by karek314** [comment]
Do you mean that not all attacker connections are dropped with 403 error ?

**Comment by Yokutto** [comment]
No connections are dropped with 403.

**Comment by karek314** [comment]
I did checked, it's working fine for me.

You should check daemon during attack
`bash ddos-deflate.sh attach`
Detaching by ctrl+a+d

Offender should appear instantly.

Please also provide your system operating version and distribution and full output from running this one liner
`cd /etc/nginx && printf "\n\n######### ls #########\n" && ls && printf "\n\n######### nginx.conf #########\n" && cat nginx.conf && printf "\n\n######### cloudflare #########\n" && cat cloudflare_settings.conf && printf "\n\n######### blacklist #########\n" && cat blacklisted_ips.conf`

**Comment by Yokutto** [comment]
I'm using a digitalocean droplet with ubuntu 16.04 php 7.1

From `bash ddos-deflate.sh attach`
![image](https://user-images.githubusercontent.com/16729837/34644145-231beb04-f318-11e7-98aa-c4e21abf11eb.png)

From big command
######### ls #########
blacklisted_ips.conf      fastcgi.conf            koi-utf     modules-available  nginx.conf.dpkg-dist  sites-available  uwsgi_params
cloudflare_settings.conf  fastcgi.conf.dpkg-dist  koi-win     modules-enabled    proxy_params          sites-enabled    win-utf
conf.d                    fastcgi_params          mime.types  nginx.conf         scgi_params           snippets


######### nginx.conf #########
user root www-data;
worker_processes 1;
lock_file /run/lock/nginx.lock;

events {
        worker_connections 2048;
}

http {
        server_tokens off;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        client_body_timeout 10s;
        client_header_timeout 10s;
        send_timeout 10s;
        keepalive_timeout 20 15;
        access_log on;
        client_max_body_size 128M;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        gzip on;
        gzip_static on;
        gzip_comp_level 4;
        gzip_disable "msie6";
        gzip_proxied any;
        gzip_types application/javascript application/json application/vnd.ms-fontobject application/x-font-ttf image/svg+xml text/css text/plain text/xml;
        gzip_vary on;

        set_real_ip_from 103.21.244.0/22;
        set_real_ip_from 103.22.200.0/22;
        set_real_ip_from 103.31.4.0/22;
        set_real_ip_from 104.16.0.0/12;
        set_real_ip_from 108.162.192.0/18;
        set_real_ip_from 131.0.72.0/22;
        set_real_ip_from 141.101.64.0/18;
        set_real_ip_from 162.158.0.0/15;
        set_real_ip_from 172.64.0.0/13;
        set_real_ip_from 173.245.48.0/20;
        set_real_ip_from 188.114.96.0/20;
        set_real_ip_from 190.93.240.0/20;
        set_real_ip_from 197.234.240.0/22;
        set_real_ip_from 198.41.128.0/17;
        set_real_ip_from 2400:cb00::/32;
        set_real_ip_from 2606:4700::/32;
        set_real_ip_from 2803:f800::/32;
        set_real_ip_from 2405:b500::/32;
        set_real_ip_from 2405:8100::/32;
        set_real_ip_from 2c0f:f248::/32;
        set_real_ip_from 2a06:98c0::/29;

        real_ip_header CF-Connecting-IP;

        fastcgi_cache_path /var/www/html/animesync.tv/cache/full levels=1:2 keys_zone=fastcgicache:10m inactive=10m max_size=64m;
        limit_conn_zone $binary_remote_addr zone=connectionlimit:10m;
        limit_req_zone $binary_remote_addr zone=ratelimitdynamic:10m rate=3r/s;
        limit_req_zone $binary_remote_addr zone=ratelimitstatic:10m rate=15r/s;
        fastcgi_cache_key $scheme$request_method$host$request_uri;
        # note: can also use HTTP headers to form the cache key, e.g.
        #fastcgi_cache_key $scheme$request_method$host$request_uri$http_x_custom_header;
        fastcgi_cache_lock on;
        fastcgi_cache_use_stale error timeout invalid_header updating http_500;
        fastcgi_cache_valid 10m;
        fastcgi_ignore_headers Cache-Control Expires Set-Cookie;

        index index.php index.html index.htm;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}


######### cloudflare #########


######### blacklist #########

**Comment by karek314** [comment]
Did you ran `bash ddos-deflate.sh install` before using ? 
It's missing
```
include blacklisted_ips.conf;
include cloudflare_settings.conf;
```

As ddos-deflate-nginx-cloudflare also automatically updates list of cloudflare ips, it's not necessary to add them manually. You should change nginx.conf to

```
user root www-data;
worker_processes 1;
lock_file /run/lock/nginx.lock;

events {
        worker_connections 2048;
}

http {
        include blacklisted_ips.conf;
        include cloudflare_settings.conf;
        server_tokens off;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        client_body_timeout 10s;
        client_header_timeout 10s;
        send_timeout 10s;
        keepalive_timeout 20 15;
        access_log on;
        client_max_body_size 128M;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        gzip on;
        gzip_static on;
        gzip_comp_level 4;
        gzip_disable "msie6";
        gzip_proxied any;
        gzip_types application/javascript application/json application/vnd.ms-fontobject application/x-font-ttf image/svg+xml text/css text/plain text/xml;
        gzip_vary on;

        fastcgi_cache_path /var/www/html/animesync.tv/cache/full levels=1:2 keys_zone=fastcgicache:10m inactive=10m max_size=64m;
        limit_conn_zone $binary_remote_addr zone=connectionlimit:10m;
        limit_req_zone $binary_remote_addr zone=ratelimitdynamic:10m rate=3r/s;
        limit_req_zone $binary_remote_addr zone=ratelimitstatic:10m rate=15r/s;
        fastcgi_cache_key $scheme$request_method$host$request_uri;
        # note: can also use HTTP headers to form the cache key, e.g.
        #fastcgi_cache_key $scheme$request_method$host$request_uri$http_x_custom_header;
        fastcgi_cache_lock on;
        fastcgi_cache_use_stale error timeout invalid_header updating http_500;
        fastcgi_cache_valid 10m;
        fastcgi_ignore_headers Cache-Control Expires Set-Cookie;

        index index.php index.html index.htm;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}
```

Is ddos-deflate.sh and daemon.php ran as root?
